export const annotationBase = {
  announcement:{label:'Aankondigingsbalk',type:'copy',guidance:'Kies één concrete servicebelofte die voor bijna iedere bezoeker geldt.',prompt:'Schrijf 5 aankondigingsbalken van maximaal 55 tekens voor [PRODUCT]. Gebruik alleen een echte verzend-, garantie- of servicebelofte. Vermijd nep-urgentie.',checklist:['Eén voordeel','Maximaal 55 tekens','Feitelijk bewijsbaar']},
  brand:{label:'Merk en logo',type:'brand',guidance:'Een korte, leesbare merknaam bouwt herkenning en brengt de bezoeker terug naar boven.',prompt:'Bedenk 12 korte merknamen voor [PRODUCTCATEGORIE]. Ze moeten makkelijk uitspreekbaar en onderscheidend zijn. Geef per naam één tagline. Controleer daarna handelsmerken en domeinen.',checklist:['Leesbaar op mobiel','Past bij de niche','Merkcheck vereist']},
  title:{label:'Producttitel',type:'copy',guidance:'De titel zegt wat het product is. De ondertitel maakt het gewenste gebruiksmoment concreet.',prompt:'Schrijf 10 producttitels voor [PRODUCT], maximaal 6 woorden. Benoem producttype en belangrijkste onderscheid. Voeg per titel een ondertitel van maximaal 10 woorden toe. Geen superlatieven zonder bewijs.',checklist:['Producttype duidelijk','Belangrijk onderscheid','Geen onbewezen claim']},
  proof:{label:'Reviewbewijs',type:'social-proof',guidance:'Score en aantal horen samen en linken naar de onderliggende reviews.',prompt:'Vat deze geverifieerde reviews van [PRODUCT] samen: [RUWE REVIEWS]. Geef 3 terugkerende thema’s, het vaakst genoemde nadeel en de transparant berekende gemiddelde score. Verzin niets.',checklist:['Echte bron','Score plus aantal','Ook nuance']},
  price:{label:'Prijs en korting',type:'offer',guidance:'Maak de huidige prijs dominant. Toon alleen een vergelijkingsprijs als die aantoonbaar geldig is.',prompt:'Maak een helder prijsblok voor [PRODUCT] met verkoopprijs [PRIJS] en geldige vergelijkingsprijs [VAN-PRIJS]. Bereken de besparing exact. Laat kortingstaal weg wanneer de referentieprijs niet aantoonbaar is.',checklist:['Prijs dominant','Besparing narekenbaar','Geen verborgen kosten']},
  bundles:{label:'Voordeelbundels',type:'offer',guidance:'Vergelijk iedere optie op dezelfde dimensies: hoeveelheid, inhoud, prijs en besparing.',prompt:'Ontwerp 3 eerlijke bundels voor [PRODUCT]. Geef per bundel: exacte inhoud, totaalprijs, prijs per stuk, doelgroep en feitelijke badge. Adviseer alleen een optie wanneer de waarde aantoonbaar beter is.',checklist:['Exacte inhoud','Zelfde vergelijkingsbasis','Selectie zichtbaar']},
  cta:{label:'Primaire koopknop',type:'conversion',guidance:'De knop beschrijft exact wat er na de klik gebeurt. Praktische geruststelling staat er direct onder.',prompt:'Schrijf 8 actieve CTA-knoppen voor [PRODUCT], maximaal 4 woorden. De tekst moet exact overeenkomen met de vervolgstap. Voeg per CTA één korte regel toe over [VERZENDING/GARANTIE].',checklist:['Actief werkwoord','Eén primaire actie','Uitkomst klopt']},
  benefits:{label:'Belangrijkste voordelen',type:'copy',guidance:'Combineer ieder gewenst resultaat met de producteigenschap die dat mogelijk maakt.',prompt:'Zet deze eigenschappen van [PRODUCT] om in 3 voordelen: [EIGENSCHAPPEN]. Geef per voordeel een kop van maximaal 5 woorden en één feitelijke uitlegzin. Behoud beperkingen.',checklist:['Resultaat plus reden','Snel scanbaar','Geen absolute claims']},
  story:{label:'Probleem en mechanisme',type:'content',guidance:'Deze sectie maakt duidelijk waarom het probleem bestaat en hoe het product praktisch helpt.',prompt:'Schrijf een probleem-mechanisme-sectie voor [PRODUCT]. Open met een herkenbaar moment, leg in gewone taal uit hoe [MECHANISME] helpt en eindig met precies 3 gebruiksstappen. Maximaal 160 woorden.',checklist:['Herkenbaar probleem','Mechanisme uitgelegd','Drie concrete stappen']},
  included:{label:'Wat zit er in de doos?',type:'content',guidance:'Een exacte inhoudslijst voorkomt onzekerheid en retouren.',prompt:'Maak een verpakkingsinhoud-sectie voor [PRODUCT] op basis van [ECHTE INHOUD]. Noem ieder onderdeel exact één keer en voeg niets toe dat niet wordt meegeleverd.',checklist:['Alles één keer','Exacte benamingen','Geen verzonnen extra’s']},
  reviews:{label:'Reviewsectie',type:'social-proof',guidance:'Gebruik uitsluitend echte feedback met context, concreet resultaat en ruimte voor nuance.',prompt:'Structureer deze echte klantfeedback voor [PRODUCT]: [RUWE REVIEWS]. Behoud betekenis en formulering, anonimiseer persoonsgegevens, verzin niets en selecteer een evenwichtige mix inclusief één genuanceerde review.',checklist:['Echte bron','Context zichtbaar','Ook nuance']},
  faq:{label:'Veelgestelde vragen',type:'content',guidance:'Beantwoord bezwaren die nog niet eerder zijn opgelost. Geef eerst het directe antwoord.',prompt:'Maak 8 FAQ’s voor [PRODUCT] uit [KLANTVRAGEN]. Begin ieder antwoord met een direct kernfeit, houd het onder 55 woorden en verzin geen beleid of productspecificaties.',checklist:['Gebaseerd op bron','Antwoord eerst','Geen herhaling']},
};

export function getAnnotations(store) {
  const shots = Object.fromEntries(store.product.media.map((media) => [media.id, {
    label: media.title,
    type: `beeldbrief · ${media.shotType}`,
    guidance: media.direction,
    prompt: media.prompt,
    checklist: [`Altijd ${media.ratio}`, `Onderwerp: ${media.subject}`, `Verplicht: ${media.mustInclude}`, `Vermijd: ${media.avoid}`],
    shot: media,
  }]));
  return { ...annotationBase, ...shots };
}
