// START HERE: students can replace the complete example store from this file.
export const store = {
  ui: {
    skipLink: 'Ga naar productinformatie',
    mainNavigationLabel: 'Hoofdnavigatie',
    mobileNavigationLabel: 'Mobiele navigatie',
    learnOn: 'Leerlaag aan',
    learnOff: 'Bekijk uitleg',
    openMenu: 'Open menu',
    closeMenu: 'Sluit menu',
    backToTop: 'terug naar boven',
    starsLabel: 'van 5 sterren',
    explanationLabel: 'Uitleg',
    productSingular: 'product',
    home: 'Home',
    breadcrumbCategory: 'Cold brew',
    galleryLabel: 'Kies productafbeelding',
    viewImage: 'Bekijk afbeelding',
    exampleReviews: 'voorbeeldreviews',
    save: 'Bespaar',
    exampleDeal: 'Voorbeelddeal',
    chooseSet: 'Kies je set',
    quantity: 'Aantal',
    decreaseQuantity: 'Aantal verlagen',
    increaseQuantity: 'Aantal verhogen',
    add: 'Voeg toe',
    shippingTrust: 'Gratis verzending',
    guaranteeTrust: '30 dagen demo-garantie',
    storySectionLabel: '01 — HET RITUEEL',
    includedSectionLabel: '02 — IN DE DOOS',
    includedTitle: 'Eén set. Alles voor morgen.',
    guaranteeSectionLabel: 'GEEN KLIKVAL, WEL DUIDELIJKHEID',
    reviewsSectionLabel: '03 — ERVARINGEN',
    reviewsTitle: 'Ochtenden van anderen.',
    basedOn: 'Gebaseerd op',
    verifiedExamplePurchase: 'Geverifieerde voorbeeldaankoop',
    previousReview: 'Vorige review',
    nextReview: 'Volgende review',
    faqSectionLabel: '04 — NOG EVEN DIT',
    faqTitle: 'Vragen voor je inschenkt.',
    faqIntro: 'Een sterke FAQ beantwoordt echte bezwaren. Deze antwoorden zijn voorbeeldinhoud.',
    footerNote: 'Onderwijstemplate · geen echte winkel · alle data is voorbeeldinhoud',
    learningDataLink: 'Open leerdata.json',
    from: 'Vanaf',
    learningLayer: 'LEERLAAG',
    checkThis: 'Controleer dit',
    aiPrompt: 'AI-PROMPT',
    copy: 'Kopieer',
    copied: 'Gekopieerd',
    attention: 'Let op',
    machineJson: 'Bekijk machine-readable JSON',
    closeExplanation: 'Sluit uitleg',
    demoCart: 'DEMO-WINKELMAND',
    cartTitle: 'Bijna morgenochtend.',
    closeCart: 'Sluit winkelmand',
    emptyCartTitle: 'Je demo-mand is leeg.',
    emptyCartText: 'Kies een set en voeg hem toe om de flow te testen.',
    continueViewing: 'Verder bekijken',
    shipping: 'Verzending',
    free: 'Gratis',
    total: 'Totaal',
    demoDisclosure: 'Oefenomgeving: deze knop rondt alleen de demonstratie af. Er wordt niets besteld of betaald.',
    finishDemo: 'Rond demo af',
    removeDemo: 'Verwijder uit demo-mand',
    demoComplete: 'Demo afgerond — er is niets besteld of betaald.',
    markerLabels: { announcement: 'Balk', logo: 'Logo', gallery: 'Galerij', title: 'Titel', proof: 'Bewijs', price: 'Prijs', offer: 'Aanbod', cta: 'CTA', benefits: 'Voordelen', process: 'Proces', guarantee: 'Garantie', reviews: 'Reviews', faq: 'FAQ' },
  },
  brand: {
    name: 'MORGENMAAK',
    tagline: 'Rust in je ochtend, smaak in je glas.',
    logoMark: 'M',
  },
  announcement: 'GRATIS VERZENDING VANAF €50 · 30 DAGEN PROBEREN',
  navigation: [
    { label: 'Zo werkt het', href: '#zo-werkt-het' },
    { label: 'Wat zit erin', href: '#in-de-doos' },
    { label: 'Reviews', href: '#reviews' },
    { label: 'Vragen', href: '#faq' },
  ],
  product: {
    eyebrow: 'Cold brew, zonder ochtendchaos',
    name: 'Cold Brew Starterset',
    subtitle: 'Zet ’m ’s avonds. Schenk ’m morgen.',
    description: 'Een glazen brewer, ultrafijn filter en startgids waarmee je in 60 seconden je cold brew voorbereidt. De koelkast doet de rest.',
    rating: 4.8,
    reviewCount: 184,
    price: 69,
    compareAtPrice: 89,
    currency: 'EUR',
    media: [
      { id: 'hero', number: '01', label: 'PRODUCTFOTO', title: 'Hero shot', direction: 'Toon het volledige product op een rustige achtergrond.', spec: '1600 × 1600 · JPG/WEBP · 1:1', alt: 'Afbeeldingsplaceholder voor de belangrijkste productfoto' },
      { id: 'detail', number: '02', label: 'DETAILFOTO', title: 'Bewijs het detail', direction: 'Zoom in op materiaal, afwerking of het belangrijkste mechanisme.', spec: '1600 × 1600 · JPG/WEBP · 1:1', alt: 'Afbeeldingsplaceholder voor een detailfoto van het product' },
      { id: 'contents', number: '03', label: 'INHOUDSFOTO', title: 'Wat krijg je?', direction: 'Leg alle onderdelen overzichtelijk naast elkaar.', spec: '1600 × 1600 · JPG/WEBP · 1:1', alt: 'Afbeeldingsplaceholder voor alle onderdelen van de set' },
      { id: 'lifestyle', number: '04', label: 'LIFESTYLE', title: 'Product in gebruik', direction: 'Laat het product in een herkenbaar gebruiksmoment zien.', spec: '1600 × 1600 · JPG/WEBP · 1:1', alt: 'Afbeeldingsplaceholder voor het product in gebruik' },
    ],
    bundles: [
      { id: 'starter', label: 'Starterset', detail: '1 brewer · 4 glazen', price: 69, badge: 'Meest gekozen' },
      { id: 'duo', label: 'Duo-set', detail: '2 brewers · 8 glazen', price: 109, compareAtPrice: 138, badge: 'Bespaar €29' },
      { id: 'brewer', label: 'Alleen de brewer', detail: '1 brewer · geen glazen', price: 49 },
    ],
    benefits: [
      { icon: 'clock', title: '60 sec. voorbereiding', text: 'Vullen, water erbij en de koelkast in.' },
      { icon: 'drop', title: 'Glad, niet bitter', text: 'Het fijne filter houdt gruis uit je glas.' },
      { icon: 'leaf', title: 'Herbruikbaar ontwerp', text: 'Geen cups, papieren filters of capsules.' },
      { icon: 'fridge', title: 'Past in je koelkastdeur', text: 'Slank formaat, lekvrije afsluiting.' },
    ],
    guarantee: {
      days: '30',
      daysLabel: 'DAGEN',
      title: '30 ochtenden proefslapen',
      text: 'Niet jouw ritueel? Stuur de set binnen 30 dagen terug. Dit is voorbeeldbeleid; pas het aan je echte voorwaarden aan.',
    },
  },
  story: {
    kicker: 'De nachtshift voor je koffie',
    title: 'Goed wakker worden begint de avond ervoor.',
    intro: 'Cold brew is geen ingewikkelde baristatruc. Met de juiste verhouding en een fijn filter maak je een zachte koffiebasis die vier dagen goed blijft.',
    steps: [
      { number: '01', title: 'Schep', text: 'Doe grof gemalen koffie in het filter.' },
      { number: '02', title: 'Schenk', text: 'Voeg koud water toe en draai het deksel vast.' },
      { number: '03', title: 'Slaap', text: 'Laat 8–12 uur trekken. Schenk ’s ochtends direct in.' },
    ],
    includedImage: { id: 'included', number: '05', label: 'OVERZICHTSFOTO', title: 'Alles wat wordt meegeleverd', direction: 'Fotografeer de complete inhoud van bovenaf en houd elk onderdeel herkenbaar.', spec: '1800 × 1400 · JPG/WEBP · 9:7', alt: 'Afbeeldingsplaceholder voor de complete inhoud van de starterset' },
    included: ['Ribbelglazen brewer van 1 liter', 'Ultrafijn roestvrijstalen filter', 'Lekvrij kobaltblauw deksel', 'Maatlepel en startgids', 'Vier stapelbare glazen'],
  },
  reviews: [
    { name: 'Noor V.', initials: 'NV', rating: 5, title: 'Mijn ochtend is echt korter', quote: 'Ik zet hem na het eten klaar en pak hem de volgende ochtend uit de deur. De koffie is helder en ik heb geen gruis onderin.', verified: true },
    { name: 'Sam K.', initials: 'SK', rating: 5, title: 'Eindelijk simpel genoeg', quote: 'De verhouding op de maatlepel voorkomt giswerk. Inmiddels maak ik op zondag meteen twee batches.', verified: true },
    { name: 'Mila D.', initials: 'MD', rating: 4, title: 'Mooi én praktisch', quote: 'Past precies in de koelkastdeur. Het filter schoonmaken kost iets meer tijd, maar dat is het me waard.', verified: true },
  ],
  faqs: [
    { question: 'Welke koffiebonen heb ik nodig?', answer: 'Elke boon werkt. Begin met een medium roast en grove maling. De startgids bevat verhoudingen voor zacht, klassiek en krachtig.' },
    { question: 'Hoe lang blijft cold brew goed?', answer: 'De voorbeeldrichtlijn is maximaal vier dagen afgedekt in de koelkast. Volg voor je eigen product altijd je geteste voedselveiligheidsadvies.' },
    { question: 'Kan alles in de vaatwasser?', answer: 'De glazen onderdelen en het filter wel. Was het deksel bij voorkeur met de hand om de afsluitring langer goed te houden.' },
    { question: 'Is dit een echte winkel?', answer: 'Nee. Dit is een interactieve onderwijstemplate. Er wordt niets afgerekend en alle productdata, reviews en voorwaarden zijn herkenbare voorbeeldinhoud.' },
  ],
  colors: {
    paper: '#f7f8f5',
    ink: '#15201c',
    cobalt: '#0b6b5d',
    tomato: '#ef6a4c',
    amber: '#c7f36b',
  },
};

// Change or extend these SVG primitives to replace every interface/product icon centrally.
export const icons = {
  clock: [{ tag: 'circle', props: { cx: 12, cy: 12, r: 9 } }, { tag: 'path', props: { d: 'M12 7v5l3 2' } }],
  drop: [{ tag: 'path', props: { d: 'M12 2S5.5 9.2 5.5 14a6.5 6.5 0 0013 0C18.5 9.2 12 2 12 2z' } }],
  leaf: [{ tag: 'path', props: { d: 'M20 4C12 4 5 8 5 15c0 3 2 5 5 5 7 0 10-8 10-16z' } }, { tag: 'path', props: { d: 'M4 21c2-6 7-10 13-13' } }],
  fridge: [{ tag: 'rect', props: { x: 6, y: 2, width: 12, height: 20, rx: 2 } }, { tag: 'path', props: { d: 'M6 10h12M9 6v2M9 13v3' } }],
  cart: [{ tag: 'path', props: { d: 'M3 4h2l2.3 10.5a2 2 0 002 1.5H18a2 2 0 001.9-1.4L22 7H7' } }, { tag: 'circle', props: { cx: 10, cy: 20, r: 1 } }, { tag: 'circle', props: { cx: 18, cy: 20, r: 1 } }],
  arrow: [{ tag: 'path', props: { d: 'M5 12h14M14 7l5 5-5 5' } }],
  check: [{ tag: 'path', props: { d: 'M5 12l4 4L19 6' } }],
  copy: [{ tag: 'rect', props: { x: 8, y: 8, width: 11, height: 11, rx: 2 } }, { tag: 'path', props: { d: 'M16 8V5a2 2 0 00-2-2H5a2 2 0 00-2 2v9a2 2 0 002 2h3' } }],
  info: [{ tag: 'circle', props: { cx: 12, cy: 12, r: 9 } }, { tag: 'path', props: { d: 'M12 11v6M12 7h.01' } }],
  close: [{ tag: 'path', props: { d: 'M5 5l14 14M19 5L5 19' } }],
  menu: [{ tag: 'path', props: { d: 'M4 7h16M4 12h16M4 17h16' } }],
  minus: [{ tag: 'path', props: { d: 'M5 12h14' } }],
  plus: [{ tag: 'path', props: { d: 'M5 12h14M12 5v14' } }],
  image: [{ tag: 'rect', props: { x: 3, y: 4, width: 18, height: 16, rx: 1 } }, { tag: 'circle', props: { cx: 8.5, cy: 9, r: 1.5 } }, { tag: 'path', props: { d: 'M4 17l5-5 3 3 2-2 6 6' } }],
  chevron: [{ tag: 'path', props: { d: 'M6 9l6 6 6-6' } }],
};

export const money = (value) => new Intl.NumberFormat('nl-NL', {
  style: 'currency', currency: store.product.currency,
}).format(value);
