'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {getAnnotations} from './content/annotations.js';
import {imageSlots} from './content/product.js';

const slotsByArea=(area)=>imageSlots.filter((slot)=>slot.area===area);
const gallery=slotsByArea('gallery'),featureSlots=slotsByArea('features'),stepSlots=slotsByArea('steps'),reviewSlots=slotsByArea('reviews').filter((slot)=>slot.id.startsWith('review-'));
const features=[
 ['VOORDEEL 01','Maak het belangrijkste voordeel direct voelbaar.','Gebruik deze brede productfoto om het grootste klantvoordeel te bewijzen. Laat het product in een rustige, geloofwaardige gebruikssituatie zien.','Lifestyle productfoto · product in gebruik · resultaat zichtbaar'],
 ['VOORDEEL 02','Laat zien waarom het product beter werkt.','Zoom in op het materiaal, mechanisme of detail dat de belofte mogelijk maakt. Dit beeld moet een twijfel wegnemen, niet alleen decoratief zijn.','Detailfoto · eigenschap en mechanisme · tastbare kwaliteit'],
 ['VOORDEEL 03','Plaats het product in het echte dagelijks leven.','Toon formaat, context en gebruiksgemak. Houd de setting herkenbaar en rustig, zodat het product altijd de hoofdrol houdt.','Contextfoto · realistische omgeving · schaal en gemak'],
];
const steps=[['01','Uitpakken','Toon hoe het product uit de verpakking komt.','Unboxing · product en verpakking'],['02','Klaarmaken','Laat één eenvoudige voorbereidingsstap zien.','Voorbereiding · één duidelijke handeling'],['03','Gebruiken','Breng het belangrijkste gebruiksmoment in beeld.','Product in gebruik · kernmoment'],['04','Resultaat','Toon het gewenste resultaat zonder onbewezen claims.','Resultaatbeeld · geloofwaardig eindmoment']];
const faqs=[['Voor wie is [PRODUCT] geschikt?','Geef een direct antwoord vanuit echte productspecificaties en benoem ook voor wie het product niet bedoeld is.'],['Hoe gebruik ik [PRODUCT]?','Vat de echte gebruiksinstructie samen in enkele concrete stappen. Verzin geen werking of resultaat.'],['Welke variant of maat kies ik?','Plaats hier een heldere keuzehulp die op echte productdata is gebaseerd.'],['Wat zit er precies in de verpakking?','Noem ieder meegeleverd onderdeel exact één keer.'],['Hoe werkt verzending en retourneren?','Vul uitsluitend je echte levertijd, retourtermijn en voorwaarden in.']];
const details=[['Details & voordelen','Leg uit wat het product is, welk probleem het oplost en welke eigenschap daarvoor zorgt.'],['Zo werkt het','Beschrijf de werking in gewone taal en voeg alleen echte stappen toe.'],['Proefperiode & garantie','Vul hier de echte proefperiode, voorwaarden en uitzonderingen in.'],['Verzendinformatie','Vul hier je echte verwerkingstijd, levertijd en verzendkosten in.']];
const reviews=[['Reviewfoto 01','Klant met product · mobiele UGC-look'],['Reviewfoto 02','Product thuis · imperfect en geloofwaardig'],['Reviewfoto 03','Close-up resultaat · natuurlijk licht']];

function Icon({name,size=20}){const p={cart:<><path d="M3 4h2l2.1 9.7a2 2 0 002 1.6h8.8a2 2 0 001.9-1.5L22 7H6.2"/><circle cx="10" cy="20" r="1"/><circle cx="18" cy="20" r="1"/></>,check:<path d="m5 12 4 4L19 6"/>,arrow:<path d="M5 12h14m-5-5 5 5-5 5"/>,image:<><rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="8.5" cy="9" r="1.5"/><path d="m4 17 5-5 3 3 2-2 6 6"/></>,shield:<path d="m12 3 7 3v5c0 5-3 8-7 10-4-2-7-5-7-10V6l7-3Z"/>,truck:<><path d="M3 6h11v10H3zM14 9h4l3 3v4h-7z"/><circle cx="7" cy="18" r="2"/><circle cx="18" cy="18" r="2"/></>,leaf:<><path d="M20 4C10 4 4 9 4 17c6 1 13-2 16-13Z"/><path d="M4 20c2-6 7-9 12-11"/></>,heart:<path d="M20.8 4.6a5.5 5.5 0 00-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 00-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 000-7.8Z"/>,close:<path d="m5 5 14 14M19 5 5 19"/>,copy:<><rect x="8" y="8" width="11" height="11" rx="2"/><path d="M16 8V5a2 2 0 00-2-2H5a2 2 0 00-2 2v9a2 2 0 002 2h3"/></>,info:<><circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/></>};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{p[name]}</svg>}
function Stars(){return <span className="stars" aria-label="Vijf sterren">★★★★★</span>}
function Placeholder({id,label,brief,ratio='1:1',mobileRatio=ratio,className='',onLearn}){return <div className={`placeholder ${className}`} data-visible-slot={id} data-learn-target={id} data-slot-ratio={ratio} data-slot-mobile-ratio={mobileRatio} data-slot-brief={brief} style={{'--ratio':ratio.replace(':',' / ')}} role="img" aria-label={`${label}: ${brief}`}><div className="placeholder__art" aria-hidden="true"><span/><i/><b/><Icon name="image" size={26}/></div><div className="placeholder__copy"><strong>{label}</strong><span>{brief}</span><small>{ratio}{mobileRatio!==ratio?` desktop · ${mobileRatio} mobiel`:''} · vervang dit vlak door jouw afbeelding</small></div>{onLearn&&<button className="placeholder__learn" type="button" onClick={onLearn}><Icon name="info" size={15}/> Beeldprompt</button>}</div>}
function Accordion({item,initial=false}){const[open,setOpen]=useState(initial);return <article className={`accordion ${open?'is-open':''}`}><h3><button type="button" onClick={()=>setOpen(!open)} aria-expanded={open}>{item[0]}<span>{open?'−':'+'}</span></button></h3>{open&&<p>{item[1]}</p>}</article>}
function Marker({id,learning,open}){return learning?<button type="button" className="learn-marker" data-learn-target={id} onClick={()=>open(id)} aria-label={`Open uitleg: ${id}`}><Icon name="info" size={16}/></button>:<span hidden data-learn-target={id}/>}

export default function App(){
 const annotations=useMemo(()=>getAnnotations(),[]),[galleryIndex,setGalleryIndex]=useState(0),[bundle,setBundle]=useState('popular'),[cart,setCart]=useState(false),[learning,setLearning]=useState(false),[activeId,setActiveId]=useState(null),[copied,setCopied]=useState(false),[mobileBar,setMobileBar]=useState(true),drawerRef=useRef(null),active=activeId?annotations[activeId]:null;
 useEffect(()=>{if(new URLSearchParams(location.search).get('learn')==='1')setLearning(true)},[]);
 useEffect(()=>{if(!cart&&!activeId)return;const close=e=>{if(e.key==='Escape'){setCart(false);setActiveId(null)}};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[cart,activeId]);
 const toggleLearn=()=>{const next=!learning;setLearning(next);if(!next)setActiveId(null);const u=new URL(location.href);next?u.searchParams.set('learn','1'):u.searchParams.delete('learn');history.replaceState({},'',u)};
 const openPrompt=id=>{setLearning(true);setActiveId(annotations[id]?id:'title');requestAnimationFrame(()=>drawerRef.current?.focus())};
 const copyPrompt=async()=>{try{await navigator.clipboard.writeText(active.prompt);setCopied(true)}catch{}setTimeout(()=>setCopied(false),1500)};
 return <div className={`wolkveld-template ${learning?'learning-on':''}`}>
  <a className="skip-link" href="#main">Ga naar productinformatie</a>
  <div className="sale-bar learnable">VANDAAG: [JOUW ACTIE OF SERVICEBELOFTE]<Marker id="announcement" learning={learning} open={openPrompt}/></div>
  <div className="benefit-bar learnable"><span><Icon name="check" size={14}/> [VOORDEEL 01]</span><span><Icon name="check" size={14}/> [VOORDEEL 02]</span><span><Icon name="check" size={14}/> [VOORDEEL 03]</span><Marker id="header-benefits" learning={learning} open={openPrompt}/></div>
  <header className="site-header" id="top"><div className="brand-target learnable"><a className="wordmark" href="#top"><i>[LOGO]</i><strong>JOUW MERKNAAM</strong></a><Marker id="brand" learning={learning} open={openPrompt}/></div><button className="cart-button" type="button" onClick={()=>setCart(true)} aria-label="Open winkelmand"><Icon name="cart" size={24}/><span>{cart?1:0}</span></button></header>
  <button className={`learning-toggle ${learning?'is-on':''}`} type="button" onClick={toggleLearn}><Icon name="info" size={17}/><span>{learning?'Uitleg aan':'Toon uitleg'}</span></button>
  <main id="main">
   <section className="product-shell section-wrap">
    <div className="gallery-column"><div className="gallery-main"><span className="discount-pill learnable">[ACTIEBADGE]<Marker id="action-badge" learning={learning} open={openPrompt}/></span><Placeholder {...gallery[galleryIndex]} className="hero-placeholder" onLearn={learning?()=>openPrompt(gallery[galleryIndex].id):null}/><div className="gallery-arrows"><button type="button" onClick={()=>setGalleryIndex((galleryIndex+gallery.length-1)%gallery.length)} aria-label="Vorige afbeelding">←</button><button type="button" onClick={()=>setGalleryIndex((galleryIndex+1)%gallery.length)} aria-label="Volgende afbeelding">→</button></div></div><div className="gallery-thumbs">{gallery.map((shot,i)=><button type="button" key={shot.id} data-learn-target={shot.id} className={`${galleryIndex===i?'is-active':''} ${learning?'learnable':''}`} onClick={()=>learning?openPrompt(shot.id):setGalleryIndex(i)} aria-label={learning?`Open beeldprompt voor ${shot.label}`:`Bekijk ${shot.label}`}><Placeholder {...shot} className="thumb-placeholder"/></button>)}</div></div>
    <div className="buy-column">
     <div className="rating-row learnable"><Stars/><strong>4,8</strong><a href="#reviews">[AANTAL] reviews</a><Marker id="proof" learning={learning} open={openPrompt}/></div>
     <div className="product-kicker learnable">[KORTE PRODUCTCATEGORIE]<Marker id="category" learning={learning} open={openPrompt}/></div>
     <div className="learnable"><h1>[JOUW PRODUCTNAAM]</h1><Marker id="title" learning={learning} open={openPrompt}/></div>
     <div className="price-placeholder learnable"><strong>[JOUW PRIJS]</strong><s>[VAN-PRIJS]</s><span>[BESPARING]</span><Marker id="price" learning={learning} open={openPrompt}/></div>
     <p className="product-intro learnable">Schrijf hier in twee of drie zinnen wat het product is, voor wie het bedoeld is en welk concreet probleem het oplost.<Marker id="intro" learning={learning} open={openPrompt}/></p>
     <ul className="icon-benefits learnable">{[['heart','[BELANGRIJKSTE VOORDEEL]'],['leaf','[TWEEDE VOORDEEL]'],['shield','[DERDE VOORDEEL]']].map(([icon,title],i)=><li key={title}><i><Icon name={icon}/></i><span><strong>{title}</strong><small>{i===0?'Korte feitelijke uitleg van het voordeel.':i===1?'Koppel het resultaat aan een producteigenschap.':'Neem een belangrijke twijfel direct weg.'}</small></span></li>)}<Marker id="benefit-list" learning={learning} open={openPrompt}/></ul>
     <fieldset className="bundle-picker learnable"><legend>KIES JE SET</legend>{[['single','1 × [PRODUCT]','Voor één gebruiksmoment','[PRIJS]',''],['popular','2 × [PRODUCT]','Voor de populairste combinatie','[BUNDELPRIJS]','MEEST GEKOZEN'],['value','3 × [PRODUCT]','De beste waarde per stuk','[BUNDELPRIJS]','BESTE WAARDE']].map(([id,title,sub,price,badge])=><label key={id} className={bundle===id?'is-selected':''}>{badge&&<em>{badge}</em>}<input type="radio" name="bundle" checked={bundle===id} onChange={()=>setBundle(id)}/><i className="radio-dot"/><span><strong>{title}</strong><small>{sub}</small></span><b>{price}</b></label>)}<Marker id="bundles" learning={learning} open={openPrompt}/></fieldset>
     <div className="stock-line learnable"><span/><strong>Op voorraad</strong> — klaar om verwerkt te worden<Marker id="stock" learning={learning} open={openPrompt}/></div>
     <div className="add-button-wrap learnable"><button className="add-button" type="button" onClick={()=>setCart(true)}>IN WINKELMAND <Icon name="arrow"/></button><Marker id="cta" learning={learning} open={openPrompt}/></div>
     <div className="payments"><span>ideal</span><span>VISA</span><span>mastercard</span><span>Pay</span><span>PayPal</span></div><p className="scarcity-note learnable"><span>●</span> [PLAATS HIER ALLEEN ECHTE VOORRAADINFORMATIE]<Marker id="stock" learning={learning} open={openPrompt}/></p>
     <div className="trust-cards learnable"><div><Icon name="truck"/><span><strong>[VERZENDVOORDEEL]</strong><small>Vul de echte levertijd in.</small></span></div><div><Icon name="shield"/><span><strong>[GARANTIE]</strong><small>Vul je echte voorwaarden in.</small></span></div><Marker id="trust" learning={learning} open={openPrompt}/></div>
     <div className="product-accordions learnable">{details.map((x,i)=><Accordion key={x[0]} item={x} initial={i===0}/>)}<Marker id="details" learning={learning} open={openPrompt}/></div>
    </div>
   </section>
   <section className="feature-story" id="waarom"><header className="section-heading learnable"><span>WAAROM KLANTEN HIERVOOR KIEZEN</span><h2>Een product dat een herkenbaar probleem oplost.</h2><p>Gebruik deze secties om voordelen te bewijzen met beeld, context en rustige uitleg.</p><Marker id="feature-heading" learning={learning} open={openPrompt}/></header><div className="feature-list section-wrap">{features.map(([eyebrow,title,copy],i)=><article className="feature-row" key={eyebrow}><Placeholder {...featureSlots[i]} onLearn={learning?()=>openPrompt(featureSlots[i].id):null}/><div className="learnable"><span>{eyebrow}</span><h3>{title}</h3><p>{copy}</p><ul><li><Icon name="check"/> Eén duidelijke bewijsfunctie</li><li><Icon name="check"/> Geen losse marketingclaim</li><li><Icon name="check"/> Product blijft herkenbaar</li></ul><Marker id={`feature-0${i+1}-copy`} learning={learning} open={openPrompt}/></div></article>)}</div></section>
   <section className="black-usp-strip learnable">{[['heart','[VOORDEEL 01]'],['leaf','[VOORDEEL 02]'],['shield','[VOORDEEL 03]'],['truck','[VOORDEEL 04]']].map(([icon,title])=><div key={title}><Icon name={icon} size={27}/><strong>{title}</strong><span>Eén korte bewijszin</span></div>)}<Marker id="usp-strip" learning={learning} open={openPrompt}/></section>
   <section className="how-section" id="gebruik"><header className="section-heading learnable"><span>HOE HET WERKT</span><h2>Van doos naar resultaat in vier heldere stappen.</h2><Marker id="steps-heading" learning={learning} open={openPrompt}/></header><div className="step-grid section-wrap learnable">{steps.map(([number,title,copy],i)=><article key={number}><Placeholder {...stepSlots[i]} onLearn={learning?()=>openPrompt(stepSlots[i].id):null}/><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}<Marker id="steps-copy" learning={learning} open={openPrompt}/></div></section>
   <section className="reviews-section" id="reviews"><header className="review-summary learnable"><span><Stars/><strong>4,8 van 5</strong></span><p>Gebaseerd op [AANTAL] geverifieerde reviews</p><Marker id="reviews-summary" learning={learning} open={openPrompt}/></header><div className="review-grid section-wrap learnable">{reviews.map(([label,brief],i)=><article key={label}><Placeholder {...reviewSlots[i]} onLearn={learning?()=>openPrompt(reviewSlots[i].id):null}/><div><Stars/><blockquote>“{i===0?'Plaats hier een korte, concrete klantreview met een zichtbaar gebruiksmoment.':i===1?'Gebruik echte feedback die één duidelijk voordeel en context benoemt.':'Laat ook nuance staan. Dat maakt de review geloofwaardiger.'}”</blockquote><strong>[KLANTNAAM]</strong><small>Geverifieerde klant</small></div></article>)}<Marker id="reviews-copy" learning={learning} open={openPrompt}/></div><div className="text-review-grid section-wrap learnable">{['CONCRETE CONTEXT','ZICHTBAAR RESULTAAT','GELOOFWAARDIGE NUANCE'].map((x,i)=><article key={x}><Stars/><blockquote>“[KORTE REVIEW MET {x}]”</blockquote><strong>[KLANTNAAM {i+1}]</strong><small>Geverifieerde klant</small></article>)}<Marker id="reviews-copy" learning={learning} open={openPrompt}/></div><aside className="expert-quote section-wrap learnable"><Placeholder {...imageSlots.find(x=>x.id==='expert-photo')} className="expert-avatar" onLearn={learning?()=>openPrompt('expert-photo'):null}/><blockquote>“Plaats hier alleen een echte quote van een relevante expert. Benoem naam, rol en geloofwaardigheid.”</blockquote><p><strong>[NAAM EXPERT]</strong><span>[FUNCTIE OF SPECIALISME]</span></p><Marker id="expert-copy" learning={learning} open={openPrompt}/></aside></section>
   <section className="guarantee-section"><div className="guarantee-banner section-wrap learnable"><div className="guarantee-seal"><strong>[XX]</strong><span>DAGEN</span></div><div><span>PROBEER ZONDER ONNODIG RISICO</span><h2>[JOUW ECHTE GARANTIE]</h2><p>Leg in gewone taal uit hoe de garantie of proefperiode werkt. Benoem termijn, voorwaarden en uitzonderingen.</p></div><Marker id="guarantee" learning={learning} open={openPrompt}/></div></section>
   <section className="faq-section" id="faq"><header className="section-heading learnable"><span>VEELGESTELDE VRAGEN</span><h2>Alles wat je nog wilt weten.</h2><Marker id="faq-heading" learning={learning} open={openPrompt}/></header><div className="faq-layout section-wrap"><Placeholder {...imageSlots.find(x=>x.id==='faq-photo')} onLearn={learning?()=>openPrompt('faq-photo'):null}/><div className="learnable">{faqs.map((x,i)=><Accordion item={x} initial={i===0} key={x[0]}/>)}<Marker id="faq-copy" learning={learning} open={openPrompt}/></div></div></section>
   <section className="final-buy section-wrap"><Placeholder {...imageSlots.find(x=>x.id==='final-thumbnail')} onLearn={learning?()=>openPrompt('final-thumbnail'):null}/><div className="learnable"><div className="rating-row"><Stars/><span>[AANTAL] reviews</span></div><h2>[JOUW PRODUCTNAAM]</h2><p>Herhaal hier in één zin het belangrijkste voordeel.</p><Marker id="final-copy" learning={learning} open={openPrompt}/></div><button type="button" onClick={()=>setCart(true)}>KIES JE BUNDEL <Icon name="arrow"/></button></section>
  </main>
  <footer className="site-footer learnable"><div className="footer-grid section-wrap"><div><a className="footer-brand" href="#top">[LOGO]<strong>JOUW MERKNAAM</strong></a><p>Schrijf hier in één korte alinea waar je merk voor staat.</p></div><div><h3>Klantenservice</h3><a href="#faq">Veelgestelde vragen</a><a href="#">Verzending</a><a href="#">Retourneren</a><a href="mailto:service@jouwdomein.nl">Contact</a></div><div><h3>Over ons</h3><a href="#waarom">Ons verhaal</a><a href="#reviews">Reviews</a><a href="#">Privacybeleid</a><a href="#">Algemene voorwaarden</a></div><div><h3>Blijf op de hoogte</h3><p>Gebruik dit blok voor een echte nieuwsbriefbelofte.</p><form onSubmit={e=>e.preventDefault()}><input type="email" aria-label="E-mailadres" placeholder="E-mailadres"/><button aria-label="Aanmelden"><Icon name="arrow"/></button></form></div></div><div className="footer-bottom section-wrap"><span>© [JAAR] [MERKNAAM]</span><div className="payments"><span>ideal</span><span>VISA</span><span>mastercard</span><span>PayPal</span></div><a href="/stores/dieren/template.json">Scrape-bare AI-data</a></div><Marker id="footer" learning={learning} open={openPrompt}/></footer>
  {mobileBar&&<div className="mobile-buy-bar learnable"><button className="mobile-buy-close" onClick={()=>setMobileBar(false)} aria-label="Sluit koopbalk">×</button><span><small>[JOUW PRODUCTNAAM]</small><strong>[JOUW PRIJS]</strong></span><button onClick={()=>setCart(true)}>KIES JE SET</button><Marker id="final-copy" learning={learning} open={openPrompt}/></div>}
  <MachineContent annotations={annotations}/>
  {cart&&<><button className="modal-backdrop" onClick={()=>setCart(false)} aria-label="Sluit winkelmand"/><aside className="cart-drawer" role="dialog" aria-modal="true" aria-labelledby="cart-title"><header><span>DEMO-WINKELMAND</span><button onClick={()=>setCart(false)} aria-label="Sluiten"><Icon name="close"/></button></header><h2 id="cart-title">Je keuze staat klaar.</h2><div className="cart-bundle learnable"><span/><div><strong>{bundle==='single'?'1 ×':bundle==='popular'?'2 ×':'3 ×'} [PRODUCT]</strong><small>Geselecteerde bundel zonder productafbeelding</small></div><b>[PRIJS]</b><Marker id="bundles" learning={learning} open={openPrompt}/></div><p>Dit is een klikbare onderwijstemplate. Er wordt niets besteld of betaald.</p><button className="cart-continue" onClick={()=>setCart(false)}>VERDER MET TEMPLATE <Icon name="arrow"/></button></aside></>}
  {active&&<><button className="modal-backdrop" onClick={()=>setActiveId(null)} aria-label="Sluit uitleg"/><aside className="prompt-drawer" ref={drawerRef} tabIndex="-1" role="dialog" aria-modal="true" aria-labelledby="prompt-title"><header><span>LEERLAAG · {active.type}</span><button onClick={()=>setActiveId(null)} aria-label="Sluiten"><Icon name="close"/></button></header><h2 id="prompt-title">{active.label}</h2><p>{active.guidance}</p><div className="prompt-checklist"><strong>Controleer dit</strong>{active.checklist.map(x=><span key={x}><Icon name="check" size={16}/>{x}</span>)}</div><div className="prompt-code"><header><span>AI-PROMPT</span><button onClick={copyPrompt}><Icon name={copied?'check':'copy'} size={15}/>{copied?'Gekopieerd':'Kopieer'}</button></header><code>{active.prompt}</code></div><a href="/stores/dieren/template.json">Bekijk alle scrape-bare prompts <Icon name="arrow" size={16}/></a></aside></>}
 </div>
}
function MachineContent({annotations}){return <section className="machine-content" aria-label="Scrape-bare templateprompts" data-template="wolkveld-product-template"><h2>AI-leerdata voor de producttemplate</h2>{Object.entries(annotations).map(([id,a])=><article key={id} data-learn-record={id} data-shot-id={a.shot?.shotId||''}><h3>{a.label}</h3><p>{a.guidance}</p><code>{a.prompt}</code>{a.shot&&<ul><li>ratio: {a.shot.ratio}</li><li>subject: {a.shot.subject}</li><li>composition: {a.shot.composition}</li><li>background: {a.shot.background}</li><li>lighting: {a.shot.lighting}</li></ul>}</article>)}</section>}
