'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowRight,Check,Copy,Heart,Image,Info,Leaf,Menu,Package,Palette,RotateCcw,ShieldCheck,ShoppingBag,Truck,X} from 'lucide-react';
import {getAnnotations} from './content/annotations.js';
import {imageSlots} from './content/product.js';

const slotsByArea=(area)=>imageSlots.filter((slot)=>slot.area===area);
const gallery=slotsByArea('gallery'),featureSlots=slotsByArea('features'),stepSlots=slotsByArea('steps'),reviewSlots=slotsByArea('reviews').filter((slot)=>slot.id.startsWith('review-'));
const features=[
 ['VOORDEEL 01','Maak het belangrijkste voordeel direct voelbaar.','Gebruik deze brede productfoto om het grootste klantvoordeel te bewijzen. Laat het product in een rustige, geloofwaardige gebruikssituatie zien.','Lifestyle productfoto · product in gebruik · resultaat zichtbaar'],
 ['VOORDEEL 02','Laat zien waarom het product beter werkt.','Zoom in op het materiaal, mechanisme of detail dat de belofte mogelijk maakt. Dit beeld moet een twijfel wegnemen, niet alleen decoratief zijn.','Detailfoto · eigenschap en mechanisme · tastbare kwaliteit'],
 ['VOORDEEL 03','Plaats het product in het echte dagelijks leven.','Toon formaat, context en gebruiksgemak. Houd de setting herkenbaar en rustig, zodat het product altijd de hoofdrol houdt.','Contextfoto · realistische omgeving · schaal en gemak'],
];
const steps=[['01','Uitpakken','Toon hoe het product uit de verpakking komt.','Unboxing · product en verpakking'],['02','Klaarmaken','Laat één eenvoudige voorbereidingsstap zien.','Voorbereiding · één duidelijke handeling'],['03','Gebruiken','Breng het belangrijkste gebruiksmoment in beeld.','Product in gebruik · kernmoment'],['04','Resultaat','Toon het gewenste resultaat zonder onbewezen claims.','Resultaatbeeld · geloofwaardig eindmoment']];
const faqs=[['Voor wie is [PRODUCT] geschikt?','Geef een direct antwoord vanuit echte productspecificaties en benoem ook voor wie het product niet bedoeld is.'],['Hoe gebruik ik [PRODUCT]?','Vat de echte gebruiksinstructie samen in enkele concrete stappen. Verzin geen werking of resultaat.'],['Welke variant of maat kies ik?','Plaats hier een heldere keuzehulp die op echte productdata is gebaseerd.'],['Wat zit er precies in de verpakking?','Noem ieder meegeleverd onderdeel exact één keer.'],['Hoe werkt verzending en retourneren?','Vul uitsluitend je echte levertijd, retourtermijn en voorwaarden in.']];
const details=[['Details & voordelen','Leg uit wat het product is, welk probleem het oplost en welke eigenschap daarvoor zorgt.'],['Zo werkt het','Beschrijf de werking in gewone taal en voeg alleen echte stappen toe.'],['Proefperiode & garantie','Vul hier de echte proefperiode, voorwaarden en uitzonderingen in.'],['Verzendinformatie','Vul hier je echte verwerkingstijd, levertijd en verzendkosten in.']];
const reviews=[['Reviewfoto 01','Klant met product · mobiele UGC-look'],['Reviewfoto 02','Product thuis · imperfect en geloofwaardig'],['Reviewfoto 03','Close-up resultaat · natuurlijk licht']];

const palettes={
 amber:{label:'Warm amber',ink:'#171511',cream:'#fbfaf6',sand:'#f1e8d9',sand2:'#e8dac5',accent:'#c9852d',muted:'#6b675f',green:'#43643d'},
 rose:{label:'Rose studio',ink:'#2b1720',cream:'#fffafb',sand:'#f6e8ec',sand2:'#ead1d9',accent:'#b65778',muted:'#735f67',green:'#4e6b5b'},
 electric:{label:'Electric blue',ink:'#101828',cream:'#f8fafc',sand:'#e9f0f7',sand2:'#d8e4ef',accent:'#1473e6',muted:'#5f6b7a',green:'#23845a'},
 sage:{label:'Natural sage',ink:'#172019',cream:'#fbfcf7',sand:'#e9efe4',sand2:'#d7e1cf',accent:'#668552',muted:'#626d62',green:'#3f7048'},
 clay:{label:'Soft clay',ink:'#2c1b17',cream:'#fffaf7',sand:'#f3e5dd',sand2:'#e8cfc1',accent:'#c46848',muted:'#79665f',green:'#55735b'},
 violet:{label:'Modern violet',ink:'#20182d',cream:'#fcfaff',sand:'#eee8f7',sand2:'#ddd1ed',accent:'#7451a6',muted:'#6d6576',green:'#39705b'},
 lemon:{label:'Playful lemon',ink:'#172019',cream:'#fffef7',sand:'#f7f0c9',sand2:'#eee29a',accent:'#d6a400',muted:'#666553',green:'#2f7751'},
 mono:{label:'Monochroom',ink:'#111111',cream:'#ffffff',sand:'#f1f1f1',sand2:'#dedede',accent:'#222222',muted:'#666666',green:'#3f6f50'},
 coral:{label:'Bright coral',ink:'#241719',cream:'#fffafa',sand:'#fbe5e1',sand2:'#f3cfc8',accent:'#e2594e',muted:'#786164',green:'#347059'},
 ocean:{label:'Deep ocean',ink:'#102329',cream:'#f7fcfc',sand:'#dfeff0',sand2:'#c6e1e3',accent:'#168597',muted:'#587076',green:'#28725b'},
};
const categoryPresets={dieren:{label:'Dieren',description:'Warm en vertrouwd',palette:'amber',font:'friendly'},beauty:{label:'Beauty',description:'Zacht en premium',palette:'rose',font:'luxury'},gadgets:{label:'Gadgets',description:'Helder en technisch',palette:'electric',font:'technical'},wellness:{label:'Wellness',description:'Rust en gezondheid',palette:'sage',font:'editorial'},fashion:{label:'Fashion',description:'Sterk en stijlvol',palette:'mono',font:'fashion'},wonen:{label:'Wonen',description:'Warm en verfijnd',palette:'clay',font:'editorial'},kids:{label:'Kids',description:'Speels en vrolijk',palette:'lemon',font:'rounded'},outdoor:{label:'Outdoor',description:'Robuust en fris',palette:'ocean',font:'bold'}};
const fontChoices={
 friendly:{label:'Modern & vriendelijk',display:"'Manrope', sans-serif",body:"'DM Sans', sans-serif"},
 luxury:{label:'Verzorgd & luxe',display:"'Playfair Display', serif",body:"'DM Sans', sans-serif"},
 technical:{label:'Strak & technisch',display:"'Space Grotesk', sans-serif",body:"'DM Sans', sans-serif"},
 editorial:{label:'Editorial serif',display:"Georgia, serif",body:"'DM Sans', sans-serif"},
 rounded:{label:'Rond & speels',display:"'Trebuchet MS', sans-serif",body:"'DM Sans', sans-serif"},
 fashion:{label:'Fashion contrast',display:"Didot, 'Times New Roman', serif",body:"Arial, sans-serif"},
 bold:{label:'Vet & compact',display:"Impact, 'Arial Black', sans-serif",body:"'DM Sans', sans-serif"},
 minimal:{label:'Minimalistisch',display:"Arial, sans-serif",body:"Arial, sans-serif"},
};
const logoTemplates=Array.from({length:20},(_,i)=>({id:`logo-${String(i+1).padStart(2,'0')}`,label:['Circle','Underline','Editorial','Capsule','Monogram','Wide','Stacked','Bracket','Stamp','Minimal','Signature','Bold','Outline','Dot','Serif','Tech','Soft','Frame','Classic','Compact'][i],style:i+1}));
const paymentCatalog=[{id:'ideal',label:'iDEAL'},{id:'visa',label:'VISA'},{id:'mastercard',label:'Mastercard'},{id:'applepay',label:'Apple Pay'},{id:'paypal',label:'PayPal'},{id:'klarna',label:'Klarna'},{id:'bancontact',label:'Bancontact'}];
const shadeHex=(hex,amount)=>{const value=parseInt(hex.slice(1),16),clamp=n=>Math.max(0,Math.min(255,n));return `#${[value>>16,(value>>8)&255,value&255].map(n=>clamp(n+amount).toString(16).padStart(2,'0')).join('')}`};
const makeTheme=(category='dieren',paletteId=categoryPresets[category]?.palette||'amber',font=categoryPresets[category]?.font||'friendly')=>{const base=palettes[paletteId]||palettes.amber;return {preset:category,category,palette:paletteId,font,...base,accentDark:shadeHex(base.accent,-42),accentLight:shadeHex(base.accent,30)}};
const safeText=(value,fallback,max)=>typeof value==='string'&&value.trim()?value.trim().slice(0,max):fallback;
const initialBuilder=(query={})=>{const category=categoryPresets[query.cat]?query.cat:'dieren',palette=palettes[query.pal]?query.pal:categoryPresets[category].palette,font=fontChoices[query.font]?query.font:categoryPresets[category].font,theme=makeTheme(category,palette,font);for(const [key,param] of [['accent','c1'],['ink','c2'],['cream','c3'],['sand','c4']])if(/^#[0-9a-f]{6}$/i.test(query[param]||''))theme[key]=query[param];theme.accentDark=shadeHex(theme.accent,-42);theme.accentLight=shadeHex(theme.accent,30);return {theme,brandName:safeText(query.brand,'JOUW MERKNAAM',28),productName:safeText(query.product,'[JOUW PRODUCTNAAM]',60),logoId:logoTemplates.some(x=>x.id===query.logo)?query.logo:'logo-01',iconStyle:['outline','rounded','solid','minimal'].includes(query.icons)?query.icons:'outline',paymentMethods:typeof query.pay==='string'?query.pay.split(',').filter(id=>paymentCatalog.some(x=>x.id===id)):paymentCatalog.slice(0,5).map(x=>x.id)}};
const trapFocus=e=>{if(e.key!=='Tab')return;const nodes=[...e.currentTarget.querySelectorAll('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')];if(!nodes.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}};

function Icon({name,size=20}){const C={cart:ShoppingBag,check:Check,arrow:ArrowRight,image:Image,palette:Palette,shield:ShieldCheck,truck:Truck,leaf:Leaf,heart:Heart,close:X,copy:Copy,info:Info,menu:Menu,reset:RotateCcw,package:Package}[name]||Info;return <C size={size} strokeWidth={1.8} aria-hidden="true"/>}
function BrandLogo({name='JOUW MERKNAAM',logoId='logo-01',footer=false}){const template=logoTemplates.find(x=>x.id===logoId)||logoTemplates[0],initials=name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();return <span className={`brand-logo logo-style-${template.style} ${footer?'is-footer':''}`} data-logo-template={template.id}><i>{template.style===5||template.style===9||template.style===14?initials:'MM'}</i><strong>{name}</strong></span>}
function PaymentStrip({methods}){return <div className="payments" data-payment-kit="morgenmaak-local-v1">{paymentCatalog.filter(x=>methods.includes(x.id)).map(item=><span key={item.id} className={`pay-${item.id}`} aria-label={item.label}>{item.id==='mastercard'?<><i/><i/></>:item.label}</span>)}</div>}
function Stars(){return <span className="stars" aria-label="Vijf sterren">★★★★★</span>}
function Placeholder({id,label,brief,ratio='1:1',mobileRatio=ratio,className='',onLearn}){return <div className={`placeholder ${className}`} data-visible-slot={id} data-learn-target={id} data-slot-ratio={ratio} data-slot-mobile-ratio={mobileRatio} data-slot-brief={brief} style={{'--ratio':ratio.replace(':',' / ')}} role="img" aria-label={`${label}: ${brief}`}><div className="placeholder__art" aria-hidden="true"><span/><i/><b/><Icon name="image" size={26}/></div><div className="placeholder__copy"><strong>{label}</strong><span>{brief}</span><small>{ratio}{mobileRatio!==ratio?` desktop · ${mobileRatio} mobiel`:''} · vervang dit vlak door jouw afbeelding</small></div>{onLearn&&<button className="placeholder__learn" type="button" onClick={onLearn}><Icon name="info" size={15}/> Beeldprompt</button>}</div>}
function Accordion({item,initial=false}){const[open,setOpen]=useState(initial);return <article className={`accordion ${open?'is-open':''}`}><h3><button type="button" onClick={()=>setOpen(!open)} aria-expanded={open}>{item[0]}<span>{open?'−':'+'}</span></button></h3>{open&&<p>{item[1]}</p>}</article>}
function Marker({id,learning,open}){return learning?<button type="button" className="learn-marker" data-learn-target={id} onClick={()=>open(id)} aria-label={`Open uitleg: ${id}`}><Icon name="info" size={16}/></button>:<span hidden data-learn-target={id}/>}

export default function App({initialConfig={}}){
 const initial=useMemo(()=>initialBuilder(initialConfig),[]),hasSharedConfig=Object.keys(initialConfig).some(key=>key!=='learn'),annotations=useMemo(()=>getAnnotations(),[]),[galleryIndex,setGalleryIndex]=useState(0),[bundle,setBundle]=useState('popular'),[cart,setCart]=useState(false),[learning,setLearning]=useState(initialConfig.learn==='1'),[activeId,setActiveId]=useState(null),[copied,setCopied]=useState(false),[styleOpen,setStyleOpen]=useState(false),[builderTab,setBuilderTab]=useState('stijl'),[styleCopied,setStyleCopied]=useState(false),[styleReady,setStyleReady]=useState(false),[theme,setTheme]=useState(initial.theme),[brandName,setBrandName]=useState(initial.brandName),[productName,setProductName]=useState(initial.productName),[logoId,setLogoId]=useState(initial.logoId),[iconStyle,setIconStyle]=useState(initial.iconStyle),[paymentMethods,setPaymentMethods]=useState(initial.paymentMethods),[mobileBar,setMobileBar]=useState(true),drawerRef=useRef(null),builderRef=useRef(null),builderOpenerRef=useRef(null),active=activeId?annotations[activeId]:null;
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('morgenmaak-builder-v2'));const slug=location.pathname.split('/').filter(Boolean).pop();if(!hasSharedConfig){if(saved?.theme?.accent&&fontChoices[saved.theme.font])setTheme(saved.theme);else if(categoryPresets[slug])setTheme(makeTheme(slug));if(saved?.brandName)setBrandName(saved.brandName);if(saved?.productName)setProductName(saved.productName);if(saved?.logoId)setLogoId(saved.logoId);if(saved?.iconStyle)setIconStyle(saved.iconStyle);if(Array.isArray(saved?.paymentMethods))setPaymentMethods(saved.paymentMethods)}}catch{}setStyleReady(true)},[]);
 useEffect(()=>{if(styleReady)localStorage.setItem('morgenmaak-builder-v2',JSON.stringify({theme,brandName,productName,logoId,iconStyle,paymentMethods}))},[theme,brandName,productName,logoId,iconStyle,paymentMethods,styleReady]);
 useEffect(()=>{if(!styleReady)return;const u=new URL(location.href),params={cat:theme.category,pal:theme.palette,font:theme.font,logo:logoId,icons:iconStyle,pay:paymentMethods.join(','),brand:brandName,product:productName,c1:theme.accent,c2:theme.ink,c3:theme.cream,c4:theme.sand};for(const[key,value]of Object.entries(params))u.searchParams.set(key,value);history.replaceState({},'',u)},[theme,brandName,productName,logoId,iconStyle,paymentMethods,styleReady]);
 useEffect(()=>{if(styleOpen)requestAnimationFrame(()=>builderRef.current?.focus());else if(styleReady)builderOpenerRef.current?.focus()},[styleOpen]);
 useEffect(()=>{if(!cart&&!activeId&&!styleOpen)return;const close=e=>{if(e.key==='Escape'){setCart(false);setActiveId(null);setStyleOpen(false)}};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[cart,activeId,styleOpen]);
 const toggleLearn=()=>{const next=!learning;setLearning(next);if(!next)setActiveId(null);const u=new URL(location.href);next?u.searchParams.set('learn','1'):u.searchParams.delete('learn');history.replaceState({},'',u)};
 const openPrompt=id=>{setLearning(true);setActiveId(annotations[id]?id:'title');requestAnimationFrame(()=>drawerRef.current?.focus())};
 const copyPrompt=async()=>{try{await navigator.clipboard.writeText(active.prompt);setCopied(true)}catch{}setTimeout(()=>setCopied(false),1500)};
 const selectCategory=id=>{const category=categoryPresets[id];setTheme(makeTheme(id,category.palette,category.font))};
 const selectPalette=id=>setTheme(current=>({...current,...makeTheme(current.category||'dieren',id,current.font),palette:id,preset:current.category||'custom'}));
 const updateColor=(key,value)=>setTheme(current=>({...current,palette:'custom',[key]:value,...(key==='accent'?{accentDark:shadeHex(value,-42),accentLight:shadeHex(value,30)}:{})}));
 const updateFont=font=>setTheme(current=>({...current,font}));
 const activeFont=fontChoices[theme.font]||fontChoices.friendly;
 const manifestPath=`/stores/${theme.category}/template.json`,aiBrief={schemaVersion:'3.0',templateId:'wolkveld-pdp',manifestUrl:manifestPath,configuration:{category:theme.category,palette:theme.palette,colors:{primary:theme.accent,dark:theme.ink,background:theme.cream,section:theme.sand},font:theme.font,brandName,productName,logoTemplate:logoId,iconPack:`lucide-${iconStyle}`,paymentMethods},instruction:'Bouw exact de sectievolgorde en selectors uit het manifest. Vervang placeholders uitsluitend met aangeleverde, verifieerbare productdata. Verzin nooit claims, prijzen, voorraad, reviews, keurmerken of garantie. Alle beeldoutputs zijn 1:1.'};
 const copyStyle=async()=>{try{await navigator.clipboard.writeText(`AI-BOUWOPDRACHT\nOpen deze configureerbare pagina: ${location.href}\nLees daarna het manifest: ${location.origin}${manifestPath}\nReconstrueer de Wolkveld-productpagina exact met de machineleesbare configuratie in de HTML.\n${JSON.stringify(aiBrief,null,2)}\nLever eerst een lijst ontbrekende invoer op; bouw daarna pas. Behoud alle data-ai-section selectors en alle 1:1 beeldverhoudingen.`);setStyleCopied(true)}catch{}setTimeout(()=>setStyleCopied(false),1500)};
 const togglePayment=id=>setPaymentMethods(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id]);
 const resetBuilder=()=>{setTheme(makeTheme());setBrandName('JOUW MERKNAAM');setProductName('[JOUW PRODUCTNAAM]');setLogoId('logo-01');setIconStyle('outline');setPaymentMethods(paymentCatalog.slice(0,5).map(x=>x.id))};
 const themeStyle={'--ink':theme.ink,'--cream':theme.cream,'--sand':theme.sand,'--sand-2':theme.sand2,'--gold':theme.accent,'--gold-dark':theme.accentDark,'--accent-light':theme.accentLight,'--muted':theme.muted,'--green':theme.green,'--font-body':activeFont.body,'--font-display':activeFont.display};
 return <div className={`wolkveld-template ${learning?'learning-on':''} icon-style-${iconStyle}`} style={themeStyle} data-style-preset={theme.preset} data-ai-template="wolkveld-pdp">
  <a className="skip-link" href="#main">Ga naar productinformatie</a>
  <div className="sale-bar learnable">VANDAAG: [JOUW ACTIE OF SERVICEBELOFTE]<Marker id="announcement" learning={learning} open={openPrompt}/></div>
  <div className="benefit-bar learnable"><span><Icon name="check" size={14}/> [VOORDEEL 01]</span><span><Icon name="check" size={14}/> [VOORDEEL 02]</span><span><Icon name="check" size={14}/> [VOORDEEL 03]</span><Marker id="header-benefits" learning={learning} open={openPrompt}/></div>
  <header className="site-header" id="top"><div className="header-tools"><button ref={builderOpenerRef} className="builder-toggle" type="button" onClick={()=>{setStyleOpen(!styleOpen);setCart(false);setActiveId(null)}} aria-expanded={styleOpen} aria-controls="builder-menu"><Icon name={styleOpen?'close':'menu'} size={20}/><span>Bouwmenu</span></button><button className={`header-learn ${learning?'is-on':''}`} type="button" onClick={toggleLearn}><Icon name="info" size={18}/><span>Prompts</span></button></div><div className="brand-target learnable"><a className="wordmark" href="#top"><BrandLogo name={brandName} logoId={logoId}/></a><Marker id="brand" learning={learning} open={openPrompt}/></div><button className="cart-button" type="button" onClick={()=>setCart(true)} aria-label="Open winkelmand"><Icon name="cart" size={24}/><span>{cart?1:0}</span></button>{styleOpen&&<BuilderMenu menuRef={builderRef} tab={builderTab} setTab={setBuilderTab} theme={theme} selectCategory={selectCategory} selectPalette={selectPalette} updateColor={updateColor} updateFont={updateFont} brandName={brandName} setBrandName={setBrandName} productName={productName} setProductName={setProductName} logoId={logoId} setLogoId={setLogoId} iconStyle={iconStyle} setIconStyle={setIconStyle} paymentMethods={paymentMethods} togglePayment={togglePayment} copyStyle={copyStyle} styleCopied={styleCopied} resetBuilder={resetBuilder} close={()=>setStyleOpen(false)} manifestPath={manifestPath}/>}</header>
  <main id="main">
   <section className="product-shell section-wrap">
    <div className="gallery-column"><div className="gallery-main"><span className="discount-pill learnable">[ACTIEBADGE]<Marker id="action-badge" learning={learning} open={openPrompt}/></span><Placeholder {...gallery[galleryIndex]} className="hero-placeholder" onLearn={learning?()=>openPrompt(gallery[galleryIndex].id):null}/><div className="gallery-arrows"><button type="button" onClick={()=>setGalleryIndex((galleryIndex+gallery.length-1)%gallery.length)} aria-label="Vorige afbeelding">←</button><button type="button" onClick={()=>setGalleryIndex((galleryIndex+1)%gallery.length)} aria-label="Volgende afbeelding">→</button></div></div><div className="gallery-thumbs">{gallery.map((shot,i)=><button type="button" key={shot.id} data-learn-target={shot.id} className={`${galleryIndex===i?'is-active':''} ${learning?'learnable':''}`} onClick={()=>learning?openPrompt(shot.id):setGalleryIndex(i)} aria-label={learning?`Open beeldprompt voor ${shot.label}`:`Bekijk ${shot.label}`}><Placeholder {...shot} className="thumb-placeholder"/></button>)}</div></div>
    <div className="buy-column">
     <div className="rating-row learnable"><Stars/><strong>4,8</strong><a href="#reviews">[AANTAL] reviews</a><Marker id="proof" learning={learning} open={openPrompt}/></div>
     <div className="product-kicker learnable">[KORTE PRODUCTCATEGORIE]<Marker id="category" learning={learning} open={openPrompt}/></div>
     <div className="learnable" data-ai-section="product.title" data-ai-prompt-id="title"><h1>{productName}</h1><Marker id="title" learning={learning} open={openPrompt}/></div>
     <div className="price-placeholder learnable"><strong>[JOUW PRIJS]</strong><s>[VAN-PRIJS]</s><span>[BESPARING]</span><Marker id="price" learning={learning} open={openPrompt}/></div>
     <p className="product-intro learnable">Schrijf hier in twee of drie zinnen wat het product is, voor wie het bedoeld is en welk concreet probleem het oplost.<Marker id="intro" learning={learning} open={openPrompt}/></p>
     <ul className="icon-benefits learnable">{[['heart','[BELANGRIJKSTE VOORDEEL]'],['leaf','[TWEEDE VOORDEEL]'],['shield','[DERDE VOORDEEL]']].map(([icon,title],i)=><li key={title}><i><Icon name={icon}/></i><span><strong>{title}</strong><small>{i===0?'Korte feitelijke uitleg van het voordeel.':i===1?'Koppel het resultaat aan een producteigenschap.':'Neem een belangrijke twijfel direct weg.'}</small></span></li>)}<Marker id="benefit-list" learning={learning} open={openPrompt}/></ul>
     <fieldset className="bundle-picker learnable"><legend>KIES JE SET</legend>{[['single','1 × [PRODUCT]','Voor één gebruiksmoment','[PRIJS]',''],['popular','2 × [PRODUCT]','Voor de populairste combinatie','[BUNDELPRIJS]','MEEST GEKOZEN'],['value','3 × [PRODUCT]','De beste waarde per stuk','[BUNDELPRIJS]','BESTE WAARDE']].map(([id,title,sub,price,badge])=><label key={id} className={bundle===id?'is-selected':''}>{badge&&<em>{badge}</em>}<input type="radio" name="bundle" checked={bundle===id} onChange={()=>setBundle(id)}/><i className="radio-dot"/><span><strong>{title}</strong><small>{sub}</small></span><b>{price}</b></label>)}<Marker id="bundles" learning={learning} open={openPrompt}/></fieldset>
     <div className="stock-line learnable"><span/><strong>Op voorraad</strong> — klaar om verwerkt te worden<Marker id="stock" learning={learning} open={openPrompt}/></div>
     <div className="add-button-wrap learnable"><button className="add-button" type="button" onClick={()=>setCart(true)}>IN WINKELMAND <Icon name="arrow"/></button><Marker id="cta" learning={learning} open={openPrompt}/></div>
     <PaymentStrip methods={paymentMethods}/><p className="scarcity-note learnable"><span>●</span> [PLAATS HIER ALLEEN ECHTE VOORRAADINFORMATIE]<Marker id="stock" learning={learning} open={openPrompt}/></p>
     <div className="trust-cards learnable"><div><Icon name="truck"/><span><strong>[VERZENDVOORDEEL]</strong><small>Vul de echte levertijd in.</small></span></div><div><Icon name="shield"/><span><strong>[GARANTIE]</strong><small>Vul je echte voorwaarden in.</small></span></div><Marker id="trust" learning={learning} open={openPrompt}/></div>
     <div className="product-accordions learnable">{details.map((x,i)=><Accordion key={x[0]} item={x} initial={i===0}/>)}<Marker id="details" learning={learning} open={openPrompt}/></div>
    </div>
   </section>
   <section className="feature-story" id="waarom"><header className="section-heading learnable"><span>WAAROM KLANTEN HIERVOOR KIEZEN</span><h2>Een product dat een herkenbaar probleem oplost.</h2><p>Gebruik deze secties om voordelen te bewijzen met beeld, context en rustige uitleg.</p><Marker id="feature-heading" learning={learning} open={openPrompt}/></header><div className="feature-list section-wrap">{features.map(([eyebrow,title,copy],i)=><article className="feature-row" key={eyebrow}><Placeholder {...featureSlots[i]} onLearn={learning?()=>openPrompt(featureSlots[i].id):null}/><div className="learnable"><span>{eyebrow}</span><h3>{title}</h3><p>{copy}</p><ul><li><Icon name="check"/> Eén duidelijke bewijsfunctie</li><li><Icon name="check"/> Geen losse marketingclaim</li><li><Icon name="check"/> Product blijft herkenbaar</li></ul><Marker id={`feature-0${i+1}-copy`} learning={learning} open={openPrompt}/></div></article>)}</div></section>
   <section className="black-usp-strip learnable">{[['heart','[VOORDEEL 01]'],['leaf','[VOORDEEL 02]'],['shield','[VOORDEEL 03]'],['truck','[VOORDEEL 04]']].map(([icon,title])=><div key={title}><Icon name={icon} size={27}/><strong>{title}</strong><span>Eén korte bewijszin</span></div>)}<Marker id="usp-strip" learning={learning} open={openPrompt}/></section>
   <section className="how-section" id="gebruik"><header className="section-heading learnable"><span>HOE HET WERKT</span><h2>Van doos naar resultaat in vier heldere stappen.</h2><Marker id="steps-heading" learning={learning} open={openPrompt}/></header><div className="step-grid section-wrap learnable">{steps.map(([number,title,copy],i)=><article key={number}><Placeholder {...stepSlots[i]} onLearn={learning?()=>openPrompt(stepSlots[i].id):null}/><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}<Marker id="steps-copy" learning={learning} open={openPrompt}/></div></section>
   <section className="reviews-section" id="reviews"><header className="review-summary learnable"><span><Stars/><strong>4,8 van 5</strong></span><p>Gebaseerd op [AANTAL] geverifieerde reviews</p><Marker id="reviews-summary" learning={learning} open={openPrompt}/></header><div className="review-grid section-wrap learnable">{reviews.map(([label,brief],i)=><article key={label}><Placeholder {...reviewSlots[i]} onLearn={learning?()=>openPrompt(reviewSlots[i].id):null}/><div><Stars/><blockquote>“{i===0?'Plaats hier een korte, concrete klantreview met een zichtbaar gebruiksmoment.':i===1?'Gebruik echte feedback die één duidelijk voordeel en context benoemt.':'Laat ook nuance staan. Dat maakt de review geloofwaardiger.'}”</blockquote><strong>[KLANTNAAM]</strong><small>Geverifieerde klant</small></div></article>)}<Marker id="reviews-copy" learning={learning} open={openPrompt}/></div><div className="text-review-grid section-wrap learnable">{['CONCRETE CONTEXT','ZICHTBAAR RESULTAAT','GELOOFWAARDIGE NUANCE'].map((x,i)=><article key={x}><Stars/><blockquote>“[KORTE REVIEW MET {x}]”</blockquote><strong>[KLANTNAAM {i+1}]</strong><small>Geverifieerde klant</small></article>)}<Marker id="reviews-copy" learning={learning} open={openPrompt}/></div><aside className="expert-quote section-wrap learnable"><Placeholder {...imageSlots.find(x=>x.id==='expert-photo')} className="expert-avatar" onLearn={learning?()=>openPrompt('expert-photo'):null}/><blockquote>“Plaats hier alleen een echte quote van een relevante expert. Benoem naam, rol en geloofwaardigheid.”</blockquote><p><strong>[NAAM EXPERT]</strong><span>[FUNCTIE OF SPECIALISME]</span></p><Marker id="expert-copy" learning={learning} open={openPrompt}/></aside></section>
   <section className="guarantee-section"><div className="guarantee-banner section-wrap learnable"><div className="guarantee-seal"><strong>[XX]</strong><span>DAGEN</span></div><div><span>PROBEER ZONDER ONNODIG RISICO</span><h2>[JOUW ECHTE GARANTIE]</h2><p>Leg in gewone taal uit hoe de garantie of proefperiode werkt. Benoem termijn, voorwaarden en uitzonderingen.</p></div><Marker id="guarantee" learning={learning} open={openPrompt}/></div></section>
   <section className="faq-section" id="faq"><header className="section-heading learnable"><span>VEELGESTELDE VRAGEN</span><h2>Alles wat je nog wilt weten.</h2><Marker id="faq-heading" learning={learning} open={openPrompt}/></header><div className="faq-layout section-wrap"><Placeholder {...imageSlots.find(x=>x.id==='faq-photo')} onLearn={learning?()=>openPrompt('faq-photo'):null}/><div className="learnable">{faqs.map((x,i)=><Accordion item={x} initial={i===0} key={x[0]}/>)}<Marker id="faq-copy" learning={learning} open={openPrompt}/></div></div></section>
   <section className="final-buy section-wrap"><Placeholder {...imageSlots.find(x=>x.id==='final-thumbnail')} onLearn={learning?()=>openPrompt('final-thumbnail'):null}/><div className="learnable"><div className="rating-row"><Stars/><span>[AANTAL] reviews</span></div><h2>{productName}</h2><p>Herhaal hier in één zin het belangrijkste voordeel.</p><Marker id="final-copy" learning={learning} open={openPrompt}/></div><button type="button" onClick={()=>setCart(true)}>KIES JE BUNDEL <Icon name="arrow"/></button></section>
  </main>
  <footer className="site-footer learnable"><div className="footer-grid section-wrap"><div><a className="footer-brand" href="#top"><BrandLogo name={brandName} logoId={logoId} footer/></a><p>Schrijf hier in één korte alinea waar je merk voor staat.</p></div><div><h3>Klantenservice</h3><a href="#faq">Veelgestelde vragen</a><a href="#">Verzending</a><a href="#">Retourneren</a><a href="mailto:service@jouwdomein.nl">Contact</a></div><div><h3>Over ons</h3><a href="#waarom">Ons verhaal</a><a href="#reviews">Reviews</a><a href="#">Privacybeleid</a><a href="#">Algemene voorwaarden</a></div><div><h3>Blijf op de hoogte</h3><p>Gebruik dit blok voor een echte nieuwsbriefbelofte.</p><form onSubmit={e=>e.preventDefault()}><input type="email" aria-label="E-mailadres" placeholder="E-mailadres"/><button aria-label="Aanmelden"><Icon name="arrow"/></button></form></div></div><div className="footer-bottom section-wrap"><span>© [JAAR] {brandName}</span><PaymentStrip methods={paymentMethods}/><a href={manifestPath}>Scrape-bare AI-data</a></div><Marker id="footer" learning={learning} open={openPrompt}/></footer>
  {mobileBar&&<div className="mobile-buy-bar learnable"><button className="mobile-buy-close" onClick={()=>setMobileBar(false)} aria-label="Sluit koopbalk">×</button><span><small>{productName}</small><strong>[JOUW PRIJS]</strong></span><button onClick={()=>setCart(true)}>KIES JE SET</button><Marker id="final-copy" learning={learning} open={openPrompt}/></div>}
  <MachineContent annotations={annotations} theme={theme} aiBrief={aiBrief}/>
  {cart&&<><button className="modal-backdrop" onClick={()=>setCart(false)} aria-label="Sluit winkelmand"/><aside className="cart-drawer" role="dialog" aria-modal="true" aria-labelledby="cart-title"><header><span>DEMO-WINKELMAND</span><button onClick={()=>setCart(false)} aria-label="Sluiten"><Icon name="close"/></button></header><h2 id="cart-title">Je keuze staat klaar.</h2><div className="cart-bundle learnable"><span/><div><strong>{bundle==='single'?'1 ×':bundle==='popular'?'2 ×':'3 ×'} [PRODUCT]</strong><small>Geselecteerde bundel zonder productafbeelding</small></div><b>[PRIJS]</b><Marker id="bundles" learning={learning} open={openPrompt}/></div><p>Dit is een klikbare onderwijstemplate. Er wordt niets besteld of betaald.</p><button className="cart-continue" onClick={()=>setCart(false)}>VERDER MET TEMPLATE <Icon name="arrow"/></button></aside></>}
  {active&&<><button className="modal-backdrop" onClick={()=>setActiveId(null)} aria-label="Sluit uitleg"/><aside className="prompt-drawer" ref={drawerRef} tabIndex="-1" role="dialog" aria-modal="true" aria-labelledby="prompt-title"><header><span>LEERLAAG · {active.type}</span><button onClick={()=>setActiveId(null)} aria-label="Sluiten"><Icon name="close"/></button></header><h2 id="prompt-title">{active.label}</h2><p>{active.guidance}</p><div className="prompt-checklist"><strong>Controleer dit</strong>{active.checklist.map(x=><span key={x}><Icon name="check" size={16}/>{x}</span>)}</div><div className="prompt-code"><header><span>AI-PROMPT</span><button onClick={copyPrompt}><Icon name={copied?'check':'copy'} size={15}/>{copied?'Gekopieerd':'Kopieer'}</button></header><code>{active.prompt}</code></div><a href={manifestPath}>Bekijk alle scrape-bare prompts <Icon name="arrow" size={16}/></a></aside></>}
 </div>
}
function BuilderMenu({menuRef,tab,setTab,theme,selectCategory,selectPalette,updateColor,updateFont,brandName,setBrandName,productName,setProductName,logoId,setLogoId,iconStyle,setIconStyle,paymentMethods,togglePayment,copyStyle,styleCopied,resetBuilder,close,manifestPath}){return <aside id="builder-menu" ref={menuRef} tabIndex="-1" className="builder-menu" role="dialog" aria-modal="true" aria-labelledby="builder-title" onKeyDown={trapFocus}><header><div><small>WOLKVELD PRODUCTTEMPLATE</small><strong id="builder-title">Pas je pagina aan</strong></div><button onClick={close} aria-label="Sluit bouwmenu"><Icon name="close"/></button></header><nav role="tablist" aria-label="Bouwmenu onderdelen">{[['stijl','Stijl'],['merk','Merk & logo'],['elementen','Iconen & betalen'],['ai','AI-export']].map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} className={tab===id?'is-active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav><div className="builder-body">
 {tab==='stijl'&&<><section className="builder-section"><h3>1. Categorie</h3><div className="category-grid">{Object.entries(categoryPresets).map(([id,p])=><button key={id} aria-pressed={theme.category===id} className={theme.category===id?'is-active':''} onClick={()=>selectCategory(id)}><strong>{p.label}</strong><small>{p.description}</small></button>)}</div></section><section className="builder-section"><h3>2. Kleurenpalet</h3><div className="palette-grid">{Object.entries(palettes).map(([id,p])=><button key={id} aria-pressed={theme.palette===id} className={theme.palette===id?'is-active':''} onClick={()=>selectPalette(id)} title={p.label}><span><i style={{background:p.ink}}/><i style={{background:p.accent}}/><i style={{background:p.sand}}/></span><small>{p.label}</small></button>)}</div></section><section className="builder-section"><h3>3. Lettertype</h3><div className="font-grid">{Object.entries(fontChoices).map(([id,font])=><button key={id} aria-pressed={theme.font===id} className={theme.font===id?'is-active':''} onClick={()=>updateFont(id)} style={{fontFamily:font.display}}><b>Aa</b><small>{font.label}</small></button>)}</div></section><details className="custom-colors"><summary>Eigen kleuren instellen</summary><div className="color-fields">{[['accent','Hoofdkleur'],['ink','Donkere kleur'],['cream','Achtergrond'],['sand','Sectiekleur']].map(([key,label])=><label key={key}><input type="color" value={theme[key]} onChange={e=>updateColor(key,e.target.value)}/><span>{label}</span><code>{theme[key].toUpperCase()}</code></label>)}</div></details></>}
 {tab==='merk'&&<><section className="builder-section field-pair"><label><span>Merknaam</span><input value={brandName} onChange={e=>setBrandName(e.target.value||'JOUW MERKNAAM')} maxLength="28"/></label><label><span>Productnaam</span><input value={productName} onChange={e=>setProductName(e.target.value||'[JOUW PRODUCTNAAM]')} maxLength="60"/></label></section><section className="builder-section"><h3>20 logo-templates</h3><p className="builder-help">Kies een bewerkbare wordmark. Je merknaam blijft gewone tekst en is dus leesbaar voor AI.</p><div className="logo-grid">{logoTemplates.map(logo=><button key={logo.id} aria-pressed={logoId===logo.id} className={logoId===logo.id?'is-active':''} onClick={()=>setLogoId(logo.id)} title={`${logo.id} · ${logo.label}`}><BrandLogo name={brandName} logoId={logo.id}/><small>{logo.label}</small></button>)}</div></section></>}
 {tab==='elementen'&&<><section className="builder-section"><h3>Lucide SVG-iconpack</h3><p className="builder-help">Lokaal gebundeld, scherp op elk scherm en scrape-baar bij naam.</p><div className="icon-style-grid">{[['outline','Outline'],['rounded','Rounded'],['solid','Solid'],['minimal','Minimal']].map(([id,label])=><button key={id} aria-pressed={iconStyle===id} className={iconStyle===id?'is-active':''} onClick={()=>setIconStyle(id)}><Icon name={id==='minimal'?'leaf':id==='solid'?'shield':'heart'} size={25}/><span>{label}</span></button>)}</div></section><section className="builder-section"><h3>Betaaliconen</h3><p className="builder-help">Klik om methodes zichtbaar of onzichtbaar te maken. Dit zijn alleen vertrouwde betaalbadges; er wordt niets afgerekend.</p><div className="payment-picker">{paymentCatalog.map(item=><button key={item.id} aria-pressed={paymentMethods.includes(item.id)} className={paymentMethods.includes(item.id)?'is-active':''} onClick={()=>togglePayment(item.id)}><span>{item.label}</span><Icon name="check" size={15}/></button>)}</div><PaymentStrip methods={paymentMethods}/></section></>}
 {tab==='ai'&&<section className="ai-export"><span className="ai-status"><i/> AI-manifest aanwezig</span><h3>Stuur de URL óf de complete brief naar je AI-bot.</h3><p>De pagina bevat alle secties, selectors, prompts, 1:1 beeldbriefings, logokeuze, iconen en betaalmethodes als machineleesbare data. Je actuele keuzes staan ook in de deelbare URL.</p><button className="copy-ai" onClick={copyStyle}><Icon name={styleCopied?'check':'copy'}/>{styleCopied?'Complete AI-brief gekopieerd':'Kopieer complete AI-brief'}</button><a href={manifestPath} target="_blank">Open scrape-baar JSON-manifest <Icon name="arrow" size={16}/></a><div className="ai-rules"><strong>De AI krijgt altijd deze regels mee</strong><span><Icon name="check"/> Behoud de Wolkveld-layout en sectievolgorde</span><span><Icon name="check"/> Alle afbeeldingen blijven exact 1:1</span><span><Icon name="check"/> Verzin nooit claims, prijzen of reviews</span><span><Icon name="check"/> Vraag ontbrekende productdata eerst uit</span></div></section>}
 </div><footer><span>Keuzes worden automatisch bewaard.</span><button onClick={resetBuilder}><Icon name="reset" size={15}/> Herstel template</button></footer></aside>}
function MachineContent({annotations,theme,aiBrief}){return <><script type="application/json" id="morgenmaak-ai-blueprint">{JSON.stringify({...aiBrief,sections:Object.entries(annotations).map(([id,a])=>({id,selector:`[data-learn-record='${id}']`,purpose:a.guidance,prompt:a.prompt,imageSpec:a.shot?{...a.shot,aspectRatio:'1:1',negativePrompt:'geen tekst, watermerk, vervorming, extra productonderdelen of onbewezen resultaat'}:null}))})}</script><section className="machine-content" aria-label="Scrape-bare templateprompts" data-template="wolkveld-product-template" data-style-preset={theme.preset} data-primary-color={theme.accent} data-dark-color={theme.ink} data-background-color={theme.cream} data-section-color={theme.sand} data-font-style={theme.font}><h2>AI-leerdata voor de producttemplate</h2><code data-style-config="current-theme">{JSON.stringify(aiBrief)}</code>{Object.entries(annotations).map(([id,a])=><article key={id} data-ai-section={id} data-ai-prompt-id={id} data-learn-record={id} data-shot-id={a.shot?.shotId||''}><h3>{a.label}</h3><p>{a.guidance}</p><code>{a.prompt}</code>{a.shot&&<ul><li>ratio: 1:1</li><li>subject: {a.shot.subject}</li><li>composition: {a.shot.composition}</li><li>background: {a.shot.background}</li><li>lighting: {a.shot.lighting}</li><li>negative prompt: geen tekst, watermerk, vervorming, extra productonderdelen of onbewezen resultaat</li></ul>}</article>)}</section></>}
